const transports=[
  {
    "APPS": "Namma Metro",
    "CONTACT_NUMBER": "180042512345",
    "MODE_OF_TRANSPORT": "Metro",
    "CARBON_INDEX_PER_KM": 30,
    "REWARD_POINTS": 100,
    "WEATHER": 1,
    "AVG_SPEED": "45kmh",
    "COST_PER_KM": 6,
    "NUMBER_OF_SEATS": 300,
    "LINK": "https://play.google.com/store/apps/details?id=com.aum.nammametro&hl=en_IN",
    "IMAGES": "/images/namma-metro.webp",
    "GREEN_POWER": false,
    "RATINGS": 4.5,
    "NUM_REVIEWS": 15
  },
  {
    "APPS": "Namma yatri",
    "CONTACT_NUMBER": "8068501060",
    "MODE_OF_TRANSPORT": "Auto Rickshaws",
    "CARBON_INDEX_PER_KM": 150,
    "REWARD_POINTS": 20,
    "WEATHER": 1,
    "AVG_SPEED": "50kmh",
    "COST_PER_KM": 15,
    "NUMBER_OF_SEATS": 3,
    "LINK": "https://play.google.com/store/apps/details?id=in.juspay.nammayatri&hl=en&gl=US",
    "IMAGES": "/images/namma-yatri.png",
    "GREEN_POWER": false,
    "RATINGS": 4.2,
    "NUM_REVIEWS": 8
  },
  {
    "APPS": "Rapido Auto",
    "CONTACT_NUMBER": "8002723900",
    "MODE_OF_TRANSPORT": "Auto Rickshaws",
    "CARBON_INDEX_PER_KM": 75,
    "REWARD_POINTS": 20,
    "WEATHER": 1,
    "AVG_SPEED": "50kmh",
    "COST_PER_KM": 12,
    "NUMBER_OF_SEATS": 2,
    "LINK": "https://www.rapido.bike/routes/[route]",
    "IMAGES": "/images/rapido-auto.jpg",
    "GREEN_POWER": false,
    "RATINGS": 4.0,
    "NUM_REVIEWS": 10
  },
  {
    "APPS": "Uber Auto",
    "CONTACT_NUMBER": "8333054871",
    "MODE_OF_TRANSPORT": "Auto Rickshaws",
    "CARBON_INDEX_PER_KM": 75,
    "REWARD_POINTS": 20,
    "WEATHER": 1,
    "AVG_SPEED": "50kmh",
    "COST_PER_KM": 13,
    "NUMBER_OF_SEATS": 2,
    "LINK": "https://www.uber.com/in/en/ride/uber-auto/",
    "IMAGES": "/images/uber-auto.webp",
    "GREEN_POWER": false,
    "RATINGS": 3.8,
    "NUM_REVIEWS": 12
  },
  {
    "APPS": "Uber",
    "CONTACT_NUMBER": "8333054871",
    "MODE_OF_TRANSPORT": "Taxis",
    "CARBON_INDEX_PER_KM": 200,
    "REWARD_POINTS": 10,
    "WEATHER": 1,
    "AVG_SPEED": "18kmh",
    "COST_PER_KM": 20,
    "NUMBER_OF_SEATS": 4,
    "LINK": "https://www.uber.com/in/en/ride/ubertaxi/",
    "IMAGES": "/images/uber-taxi.jpg",
    "GREEN_POWER": false,
    "RATINGS": 4.1,
    "NUM_REVIEWS": 15
  },
  {
    "APPS": "Ola Cabs",
    "CONTACT_NUMBER": "918046655300",
    "MODE_OF_TRANSPORT": "Taxis",
    "CARBON_INDEX_PER_KM": 180,
    "REWARD_POINTS": 10,
    "WEATHER": 1,
    "AVG_SPEED": "17kmh",
    "COST_PER_KM": 18,
    "NUMBER_OF_SEATS": 4,
    "LINK": "https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwixsff94-2DAxXd4TgGHVpHAHYQjBB6BAgIEAE&url=https%3A%2F%2Fbook.olacabs.com%2F%3FserviceType%3Dp2p%26when%3DNOW%26pickup_name%3DPlease%2520select%2520the%2520location%26drop_lat%3D16.3105174%26drop_lng%3D80.428896%26drop_name%3DInspirepath%2520Overseas%2520Consultancy%252C%2520Lakshmipuram%2520Main%2520Road%2520Ashok%2520Nagar%2520Guntur%2520Andhra%2520Pradesh%2520India%26pickup%3D%26lat%3D16.5321909%26lng%3D80.5327988&usg=AOvVaw1BA2GLlMbSUXYHW9cNwMu5&opi=89978449",
    "IMAGES": "/images/ola-cab.jpg",
    "GREEN_POWER": false,
    "RATINGS": 4.0,
    "NUM_REVIEWS": 10
  },
  {
    "APPS": "Ola Auto",
    "CONTACT_NUMBER": "918067350900",
    "MODE_OF_TRANSPORT": "Auto Rickshaws",
    "CARBON_INDEX_PER_KM": 75,
    "REWARD_POINTS": 20,
    "WEATHER": 1,
    "AVG_SPEED": "50kmh",
    "COST_PER_KM": 14,
    "NUMBER_OF_SEATS": 3,
    "LINK": "https://book.olacabs.com/",
    "IMAGES": "/images/ola-auto.jpg",
    "GREEN_POWER": false,
    "RATINGS": 3.7,
    "NUM_REVIEWS": 8
  },
  {
    "APPS": "Meru Cabs",
    "CONTACT_NUMBER": "44224422",
    "MODE_OF_TRANSPORT": "Taxis",
    "CARBON_INDEX_PER_KM": 180,
    "REWARD_POINTS": 10,
    "WEATHER": 1,
    "AVG_SPEED": "27kmh",
    "COST_PER_KM": 19,
    "NUMBER_OF_SEATS": 4,
    "LINK": "https://www.meru.in/",
    "IMAGES": "/images/meru-cabs.jpg",
    "GREEN_POWER": false,
    "RATINGS": 4.2,
    "NUM_REVIEWS": 12
  },
  {
    "APPS": "Fasttrack",
    "CONTACT_NUMBER": "28889999",
    "MODE_OF_TRANSPORT": "Electric Taxis",
    "CARBON_INDEX_PER_KM": 30,
    "REWARD_POINTS": 80,
    "WEATHER": 1,
    "AVG_SPEED": "25kmh",
    "COST_PER_KM": 17,
    "NUMBER_OF_SEATS": 4,
    "LINK": "https://fasttrackdroptaxi.com/",
    "IMAGES": "/images/fasttrack.png",
    "GREEN_POWER": true,
    "RATINGS": 4.8,
    "NUM_REVIEWS": 18
  },
  {
    "APPS": "Mega Cabs",
    "CONTACT_NUMBER": "9350011111",
    "MODE_OF_TRANSPORT": "Electric Taxis",
    "CARBON_INDEX_PER_KM": 25,
    "REWARD_POINTS": 80,
    "WEATHER": 1,
    "AVG_SPEED": "35kmh",
    "COST_PER_KM": 16,
    "NUMBER_OF_SEATS": 4,
    "LINK": "https://stg.megacabs.com/",
    "IMAGES": "/images/mega.png",
    "GREEN_POWER": true,
    "RATINGS": 4.5,
    "NUM_REVIEWS": 15
  },
  {
    "APPS": "Yulu",
    "CONTACT_NUMBER": "8099860061",
    "MODE_OF_TRANSPORT": "Battery Cycles",
    "CARBON_INDEX_PER_KM": 8,
    "REWARD_POINTS": 40,
    "WEATHER": 0,
    "AVG_SPEED": "23kmh",
    "COST_PER_KM": 5,
    "NUMBER_OF_SEATS": 1,
    "LINK": "https://www.yulu.bike/",
    "IMAGES": "/images/yulu.webp",
    "GREEN_POWER": true,
    "RATINGS": 4.3,
    "NUM_REVIEWS": 14
  },
  {
    "APPS": "ByKe Mania",
    "CONTACT_NUMBER": "8668437211",
    "MODE_OF_TRANSPORT": "Pedal Cycles",
    "CARBON_INDEX_PER_KM": 10,
    "REWARD_POINTS": 50,
    "WEATHER": 0,
    "AVG_SPEED": "20kmh",
    "COST_PER_KM": 3,
    "NUMBER_OF_SEATS": 1,
    "LINK": "https://www.bykemania.com/",
    "IMAGES": "/images/byke-mania.webp",
    "GREEN_POWER": true,
    "RATINGS": 4.6,
    "NUM_REVIEWS": 20
  },
  {
    "APPS": "Cycle2Go",
    "CONTACT_NUMBER": "8099860061",
    "MODE_OF_TRANSPORT": "Pedal Cycles",
    "CARBON_INDEX_PER_KM": 12,
    "REWARD_POINTS": 50,
    "WEATHER": 0,
    "AVG_SPEED": "21kmh",
    "COST_PER_KM": 4,
    "NUMBER_OF_SEATS": 1,
    "LINK": "https://www.cycle2go.in/home",
    "IMAGES": "/images/cycle2go.svg",
    "GREEN_POWER": true,
    "RATINGS": 4.1,
    "NUM_REVIEWS": 16
  },
  {
    "APPS": "Zoomcar",
    "CONTACT_NUMBER": "18004192500",
    "MODE_OF_TRANSPORT": "Rental Cars",
    "CARBON_INDEX_PER_KM": 20,
    "REWARD_POINTS": 35,
    "WEATHER": 1,
    "AVG_SPEED": "35kmh",
    "COST_PER_KM": 25,
    "NUMBER_OF_SEATS": 5,
    "LINK": "https://www.zoomcar.com/in/bangalore",
    "IMAGES": "/images/zoomcar.svg",
    "GREEN_POWER": false,
    "RATINGS": 3.8,
    "NUM_REVIEWS": 9
  },
  {
    "APPS": "SparkCars",
    "CONTACT_NUMBER": "9250035555",
    "MODE_OF_TRANSPORT": "Rental Electric Cars",
    "CARBON_INDEX_PER_KM": 18,
    "REWARD_POINTS": 70,
    "WEATHER": 1,
    "AVG_SPEED": "35kmh",
    "COST_PER_KM": 28,
    "NUMBER_OF_SEATS": 5,
    "LINK": "https://sparkcars.in/",
    "IMAGES": "/images/spark-cars.png",
    "GREEN_POWER": true,
    "RATINGS": 4.4,
    "NUM_REVIEWS": 11
  },
  {
    "APPS": "Revv It",
    "CONTACT_NUMBER": "08061933715",
    "MODE_OF_TRANSPORT": "Rental Cars",
    "CARBON_INDEX_PER_KM": 22,
    "REWARD_POINTS": 35,
    "WEATHER": 1,
    "AVG_SPEED": "35kmh",
    "COST_PER_KM": 24,
    "NUMBER_OF_SEATS": 5,
    "LINK": "https://www.revv.co.in/car-rental/bangalore",
    "IMAGES": "/images/revv.jpg",
    "GREEN_POWER": false,
    "RATINGS": 4.0,
    "NUM_REVIEWS": 7
  },
  {
    "APPS": "ECO Mobility",
    "CONTACT_NUMBER": "9555997650",
    "MODE_OF_TRANSPORT": "Rental Electric Cars",
    "CARBON_INDEX_PER_KM": 16,
    "REWARD_POINTS": 70,
    "WEATHER": 1,
    "AVG_SPEED": "35kmh",
    "COST_PER_KM": 26,
    "NUMBER_OF_SEATS": 5,
    "LINK": "https://www.ecorentacar.com/cities/bengaluru-rental-service/",
    "IMAGES": "/images/ecorent.png",
    "GREEN_POWER": true,
    "RATINGS": 4.2,
    "NUM_REVIEWS": 13
  },
  {
    "APPS": "BMTC",
    "CONTACT_NUMBER": "08022483777",
    "MODE_OF_TRANSPORT": "Bus",
    "CARBON_INDEX_PER_KM": 50,
    "REWARD_POINTS": 75,
    "WEATHER": 1,
    "AVG_SPEED": "88kmh",
    "COST_PER_KM": 8,
    "NUMBER_OF_SEATS": 50,
    "LINK": "https://blog.tummoc.com/book-bmtc-bus-passes-online-on-tummoc/",
    "IMAGES": "/images/bmtc.png",
    "GREEN_POWER": false,
    "RATINGS": 4.5,
    "NUM_REVIEWS": 18
  },
  {
    "APPS": "ONN Bikes",
    "CONTACT_NUMBER": "8099860061",
    "MODE_OF_TRANSPORT": "Rental Bikes",
    "CARBON_INDEX_PER_KM": 10,
    "REWARD_POINTS": 25,
    "WEATHER": 0,
    "AVG_SPEED": "18kmh",
    "COST_PER_KM": 5,
    "NUMBER_OF_SEATS": 2,
    "LINK": "https://www.onnbikes.com/bike-rental-bangalore.html#",
    "IMAGES": "/images/onn-bikes.jpg",
    "GREEN_POWER": false,
    "RATINGS": 3.9,
    "NUM_REVIEWS": 10
  },
  {
    "APPS": "Royal Brothers",
    "CONTACT_NUMBER": "9019595595",
    "MODE_OF_TRANSPORT": "Rental Bikes",
    "CARBON_INDEX_PER_KM": 9,
    "REWARD_POINTS": 25,
    "WEATHER": 0,
    "AVG_SPEED": "18kmh",
    "COST_PER_KM": 5,
    "NUMBER_OF_SEATS": 2,
    "LINK": "https://www.royalbrothers.com/bangalore/bike-rentals?utm_source=google&utm_medium=cpc&utm_campaign=Search-Daily-Rental-Bangalore-Brand&utm_campaign=Search+Daily+Rental+Bangalore+Brand&utm_medium=ppc&utm_source=adwords&utm_term=royal%20brothers%20bike%20rentals&hsa_mt=e&hsa_ad=442095758873&hsa_cam=10289128712&hsa_kw=royal%20brothers%20bike%20rentals&hsa_src=g&hsa_grp=97811531410&hsa_net=adwords&hsa_tgt=aud-874218889105:kwd-389968982636&hsa_acc=8196859737&hsa_ver=3&gad_source=1&gclid=Cj0KCQiA-62tBhDSARIsAO7twbZTBh4pnRO3rqXI6kglhe7_OgTD4OmAM-p4FDggdIiyARe6kNSg54saAizKEALw_wcB",
    "IMAGES": "/images/royal-bro.avif",
    "GREEN_POWER": false,
    "RATINGS": 4.1,
    "NUM_REVIEWS": 15
  },
  {
    "APPS": "Scoo EV",
    "CONTACT_NUMBER": "08378007800",
    "MODE_OF_TRANSPORT": "Electric Rental Bikes",
    "CARBON_INDEX_PER_KM": 7,
    "REWARD_POINTS": 50,
    "WEATHER": 0,
    "AVG_SPEED": "18kmh",
    "COST_PER_KM": 6,
    "NUMBER_OF_SEATS": 2,
    "LINK": "https://scooev.com/",
    "IMAGES": "/images/scoo.jpg",
    "GREEN_POWER": true,
    "RATINGS": 4.3,
    "NUM_REVIEWS": 12
  },
  {
    "APPS": "Zypp Electric",
    "CONTACT_NUMBER": "08061933715",
    "MODE_OF_TRANSPORT": "Electric Rental Bikes",
    "CARBON_INDEX_PER_KM": 6,
    "REWARD_POINTS": 50,
    "WEATHER": 0,
    "AVG_SPEED": "18kmh",
    "COST_PER_KM": 7,
    "NUMBER_OF_SEATS": 2,
    "LINK": "https://zypp.app/escooter-rental",
    "IMAGES": "/images/zypp.webp",
    "GREEN_POWER": true,
    "RATINGS": 4.2,
    "NUM_REVIEWS": 10
  },
  {
    "APPS": "Rapido Scooter",
    "CONTACT_NUMBER": "8002723900",
    "MODE_OF_TRANSPORT": "Bike Taxis",
    "CARBON_INDEX_PER_KM": 20,
    "REWARD_POINTS": 40,
    "WEATHER": 0,
    "AVG_SPEED": "50kmh",
    "COST_PER_KM": 18,
    "NUMBER_OF_SEATS": 2,
    "LINK": "https://www.rapido.bike/",
    "IMAGES": "/images/rapido.gif",
    "GREEN_POWER": false,
    "RATINGS": 3.8,
    "NUM_REVIEWS": 8
  },
  {
    "APPS": "BMTC Electric",
    "CONTACT_NUMBER": "08022483777",
    "MODE_OF_TRANSPORT": "Electric Buses",
    "CARBON_INDEX_PER_KM": 12,
    "REWARD_POINTS": 90,
    "WEATHER": 1,
    "AVG_SPEED": "30kmh",
    "COST_PER_KM": 10,
    "NUMBER_OF_SEATS": 50,
    "LINK": "https://blog.tummoc.com/how-to-find-bmtc-bus-timings-routes-more-on-the-tummoc-app/",
    "IMAGES": "/images/bmtc-e.webp",
    "GREEN_POWER": true,
    "RATINGS": 4.5,
    "NUM_REVIEWS": 15
  }
]
export default transports 