const transports=[
  {
    "APPS": "Namma Metro",
    "CONTACT_NUMBER": "180042512345",
    "MODE_OF_TRANSPORT": "Metro",
    "CARBON_INDEX_PER_KM": 30,
    "REWARD_POINTS": 100,
    "WEATHER": 1,
    "AVG_SPEED": "45kmh",
    "COST_PER_KM": 6,
    "NUMBER_OF_SEATS": 300,
    "LINK": "https://www.nammametro.in",
    "IMAGES": "/images/img1.webp",
    "GREEN_POWER": false
  },
  {
    "APPS": "Namma yatri",
    "CONTACT_NUMBER": "8068501060",
    "MODE_OF_TRANSPORT": "Auto Rickshaws",
    "CARBON_INDEX_PER_KM": 150,
    "REWARD_POINTS": 20,
    "WEATHER": 1,
    "AVG_SPEED": "50kmh",
    "COST_PER_KM": 15,
    "NUMBER_OF_SEATS": 3,
    "LINK": "https://www.nammayatri.com",
    "IMAGES": "/images/namma_yatri2.avif",
    "GREEN_POWER": false
  },
  {
    "APPS": "Rapido Auto",
    "CONTACT_NUMBER": "8002723900",
    "MODE_OF_TRANSPORT": "Auto Rickshaws",
    "CARBON_INDEX_PER_KM": 75,
    "REWARD_POINTS": 20,
    "WEATHER": 1,
    "AVG_SPEED": "50kmh",
    "COST_PER_KM": 12,
    "NUMBER_OF_SEATS": 2,
    "LINK": "https://www.rapido.com",
    "IMAGES": "/images/img2.png",
    "GREEN_POWER": false
  },
  {
    "APPS": "Uber Auto",
    "CONTACT_NUMBER": "8333054871",
    "MODE_OF_TRANSPORT": "Auto Rickshaws",
    "CARBON_INDEX_PER_KM": 75,
    "REWARD_POINTS": 20,
    "WEATHER": 1,
    "AVG_SPEED": "50kmh",
    "COST_PER_KM": 13,
    "NUMBER_OF_SEATS": 2,
    "LINK": "https://www.uber.com",
    "IMAGES": "/images/img3.png",
    "GREEN_POWER": false
  },
  {
    "APPS": "Uber",
    "CONTACT_NUMBER": "8333054871",
    "MODE_OF_TRANSPORT": "Taxis",
    "CARBON_INDEX_PER_KM": 200,
    "REWARD_POINTS": 10,
    "WEATHER": 1,
    "AVG_SPEED": "18kmh",
    "COST_PER_KM": 20,
    "NUMBER_OF_SEATS": 4,
    "LINK": "https://www.uber.com",
    "IMAGES": "/images/img4.png",
    "GREEN_POWER": false
  },
  {
    "APPS": "Ola Cabs",
    "CONTACT_NUMBER": "918046655300",
    "MODE_OF_TRANSPORT": "Taxis",
    "CARBON_INDEX_PER_KM": 180,
    "REWARD_POINTS": 10,
    "WEATHER": 1,
    "AVG_SPEED": "17kmh",
    "COST_PER_KM": 18,
    "NUMBER_OF_SEATS": 4,
    "LINK": "https://www.olacabs.com",
    "IMAGES": "/images/img5.png",
    "GREEN_POWER": false
  },
  {
    "APPS": "Ola Auto",
    "CONTACT_NUMBER": "918067350900",
    "MODE_OF_TRANSPORT": "Auto Rickshaws",
    "CARBON_INDEX_PER_KM": 75,
    "REWARD_POINTS": 20,
    "WEATHER": 1,
    "AVG_SPEED": "50kmh",
    "COST_PER_KM": 14,
    "NUMBER_OF_SEATS": 3,
    "LINK": "https://www.olacabs.com",
    "IMAGES": "/images/img6.png",
    "GREEN_POWER": false
  },
  {
    "APPS": "Meru Cabs",
    "CONTACT_NUMBER": "44224422",
    "MODE_OF_TRANSPORT": "Taxis",
    "CARBON_INDEX_PER_KM": 180,
    "REWARD_POINTS": 10,
    "WEATHER": 1,
    "AVG_SPEED": "27kmh",
    "COST_PER_KM": 19,
    "NUMBER_OF_SEATS": 4,
    "LINK": "https://www.merucabs.com",
    "IMAGES": "/images/img7.png",
    "GREEN_POWER": false
  },
  {
    "APPS": "Fasttrack",
    "CONTACT_NUMBER": "28889999",
    "MODE_OF_TRANSPORT": "Electric Taxis",
    "CARBON_INDEX_PER_KM": 30,
    "REWARD_POINTS": 80,
    "WEATHER": 1,
    "AVG_SPEED": "25kmh",
    "COST_PER_KM": 17,
    "NUMBER_OF_SEATS": 4,
    "LINK": "https://www.fasttrack.in",
    "IMAGES": "/images/img8.png",
    "GREEN_POWER": true
  },
  {
    "APPS": "Mega Cabs",
    "CONTACT_NUMBER": "9350011111",
    "MODE_OF_TRANSPORT": "Electric Taxis",
    "CARBON_INDEX_PER_KM": 25,
    "REWARD_POINTS": 80,
    "WEATHER": 1,
    "AVG_SPEED": "35kmh",
    "COST_PER_KM": 16,
    "NUMBER_OF_SEATS": 4,
    "LINK": "https://www.megacabs.com",
    "IMAGES": "/images/img9.png",
    "GREEN_POWER": true
  },
  {
    "APPS": "Yulu",
    "CONTACT_NUMBER": "8099860061",
    "MODE_OF_TRANSPORT": "Battery Cycles",
    "CARBON_INDEX_PER_KM": 8,
    "REWARD_POINTS": 40,
    "WEATHER": 0,
    "AVG_SPEED": "23kmh",
    "COST_PER_KM": 5,
    "NUMBER_OF_SEATS": 1,
    "LINK": "https://www.yulu.bike",
    "IMAGES": "/images/img10.png",
    "GREEN_POWER": true
  },
  {
    "APPS": "Bounce",
    "CONTACT_NUMBER": "8668437211",
    "MODE_OF_TRANSPORT": "Pedal Cycles",
    "CARBON_INDEX_PER_KM": 10,
    "REWARD_POINTS": 50,
    "WEATHER": 0,
    "AVG_SPEED": "20kmh",
    "COST_PER_KM": 3,
    "NUMBER_OF_SEATS": 1,
    "LINK": "https://www.bounce.bike",
    "IMAGES": "/images/img11.png",
    "GREEN_POWER": true
  },
  {
    "APPS": "Cyclops",
    "CONTACT_NUMBER": "8099860061",
    "MODE_OF_TRANSPORT": "Pedal Cycles",
    "CARBON_INDEX_PER_KM": 12,
    "REWARD_POINTS": 50,
    "WEATHER": 0,
    "AVG_SPEED": "21kmh",
    "COST_PER_KM": 4,
    "NUMBER_OF_SEATS": 1,
    "LINK": "https://www.cyclops.com",
    "IMAGES": "/images/img12.png",
    "GREEN_POWER": true
  },
  {
    "APPS": "Zoomcar",
    "CONTACT_NUMBER": "18004192500",
    "MODE_OF_TRANSPORT": "Rental Cars",
    "CARBON_INDEX_PER_KM": 20,
    "REWARD_POINTS": 35,
    "WEATHER": 1,
    "AVG_SPEED": "35kmh",
    "COST_PER_KM": 25,
    "NUMBER_OF_SEATS": 5,
    "LINK": "https://www.zoomcar.com",
    "IMAGES": "/images/img14.png",
    "GREEN_POWER": false
  },
  {
    "APPS": "Revv",
    "CONTACT_NUMBER": "9250035555",
    "MODE_OF_TRANSPORT": "Rental Electric Cars",
    "CARBON_INDEX_PER_KM": 18,
    "REWARD_POINTS": 70,
    "WEATHER": 1,
    "AVG_SPEED": "35kmh",
    "COST_PER_KM": 28,
    "NUMBER_OF_SEATS": 5,
    "LINK": "https://www.revv.co.in",
    "IMAGES": "/images/img15.png",
    "GREEN_POWER": true
  },
  {
    "APPS": "Drivezy",
    "CONTACT_NUMBER": "08061933715",
    "MODE_OF_TRANSPORT": "Rental Cars",
    "CARBON_INDEX_PER_KM": 22,
    "REWARD_POINTS": 35,
    "WEATHER": 1,
    "AVG_SPEED": "35kmh",
    "COST_PER_KM": 24,
    "NUMBER_OF_SEATS": 5,
    "LINK": "https://www.drivezy.com",
    "IMAGES": "/images/img16.png",
    "GREEN_POWER": false
  },
  {
    "APPS": "Carzon Rent",
    "CONTACT_NUMBER": "9555997650",
    "MODE_OF_TRANSPORT": "Rental Electric Cars",
    "CARBON_INDEX_PER_KM": 16,
    "REWARD_POINTS": 70,
    "WEATHER": 1,
    "AVG_SPEED": "35kmh",
    "COST_PER_KM": 26,
    "NUMBER_OF_SEATS": 5,
    "LINK": "https://www.carzonrent.com",
    "IMAGES": "/images/img17.png",
    "GREEN_POWER": true
  },
  {
    "APPS": "BMTC",
    "CONTACT_NUMBER": "08022483777",
    "MODE_OF_TRANSPORT": "Bus",
    "CARBON_INDEX_PER_KM": 50,
    "REWARD_POINTS": 75,
    "WEATHER": 1,
    "AVG_SPEED": "88kmh",
    "COST_PER_KM": 8,
    "NUMBER_OF_SEATS": 50,
    "LINK": "https://www.mybmtc.com",
    "IMAGES": "/images/img18.png",
    "GREEN_POWER": false
  },
  {
    "APPS": "Vogo",
    "CONTACT_NUMBER": "8099860061",
    "MODE_OF_TRANSPORT": "Rental Bikes",
    "CARBON_INDEX_PER_KM": 10,
    "REWARD_POINTS": 25,
    "WEATHER": 0,
    "AVG_SPEED": "18kmh",
    "COST_PER_KM": 5,
    "NUMBER_OF_SEATS": 2,
    "LINK": "https://www.vogo.in",
    "IMAGES": "/images/img20.png",
    "GREEN_POWER": false
  },
  {
    "APPS": "Royal Brothers",
    "CONTACT_NUMBER": "9019595595",
    "MODE_OF_TRANSPORT": "Rental Bikes",
    "CARBON_INDEX_PER_KM": 9,
    "REWARD_POINTS": 25,
    "WEATHER": 0,
    "AVG_SPEED": "18kmh",
    "COST_PER_KM": 5,
    "NUMBER_OF_SEATS": 2,
    "LINK": "https://www.royalbrothers.com",
    "IMAGES": "/images/img21.png",
    "GREEN_POWER": false
  },
  {
    "APPS": "ONN Bikes",
    "CONTACT_NUMBER": "08378007800",
    "MODE_OF_TRANSPORT": "Electric Rental Bikes",
    "CARBON_INDEX_PER_KM": 7,
    "REWARD_POINTS": 50,
    "WEATHER": 0,
    "AVG_SPEED": "18kmh",
    "COST_PER_KM": 6,
    "NUMBER_OF_SEATS": 2,
    "LINK": "https://www.onnbikes.com",
    "IMAGES": "/images/img22.png",
    "GREEN_POWER": true
  },
  {
    "APPS": "Drivezy",
    "CONTACT_NUMBER": "08061933715",
    "MODE_OF_TRANSPORT": "Electric Rental Bikes",
    "CARBON_INDEX_PER_KM": 6,
    "REWARD_POINTS": 50,
    "WEATHER": 0,
    "AVG_SPEED": "18kmh",
    "COST_PER_KM": 7,
    "NUMBER_OF_SEATS": 2,
    "LINK": "https://www.drivezy.com",
    "IMAGES": "/images/img23.png",
    "GREEN_POWER": true
  },
  {
    "APPS": "Rapido Scooter",
    "CONTACT_NUMBER": "8002723900",
    "MODE_OF_TRANSPORT": "Bike Taxis",
    "CARBON_INDEX_PER_KM": 20,
    "REWARD_POINTS": 40,
    "WEATHER": 0,
    "AVG_SPEED": "50kmh",
    "COST_PER_KM": 18,
    "NUMBER_OF_SEATS": 2,
    "LINK": "https://www.rapido.com",
    "IMAGES": "/images/img24.png",
    "GREEN_POWER": false
  },
  {
    "APPS": "BMTC Electric",
    "CONTACT_NUMBER": "08022483777",
    "MODE_OF_TRANSPORT": "Electric Buses",
    "CARBON_INDEX_PER_KM": 12,
    "REWARD_POINTS": 90,
    "WEATHER": 1,
    "AVG_SPEED": "30kmh",
    "COST_PER_KM": 10,
    "NUMBER_OF_SEATS": 50,
    "LINK": "https://www.mybmtc.com",
    "IMAGES": "/images/img25.png",
    "GREEN_POWER": true
  }
]
export default transports 